### ISSUE TITLE
 Missing required property \"nonce\" for transfer Generated\\Shared\\Transfer\\BraintreePaymentTransfer

### ISSUE THREAD

**Issue by gengjozsef** [spryker-eco/braintree#10]
Hi,

When i use Braintree with other Payment methods, if i select a payment method other than a Braintree Type (for example a custom type: Prepayment), after try to place the order i get the following error:

 Missing required property \"nonce\" for transfer Generated\\Shared\\Transfer\\BraintreePaymentTransfer

The Error occures because the Plugins: BraintreePreCheckPlugin, BraintreePostSavePlugin, BraintreeSaveOrderPlugin is executed even if the choosen Payment method is not a  Braintree type and some parameters are not set.

Best Regards,
Jozsef

**Comment by darius-telycenas** [comment]
Support questions should go to support.spryker.com

Your issue is created there: https://support.spryker.com/hc/en-us/community/posts/360043364692-Braintree-Missing-required-property-nonce-for-BraintreePaymentTransfer-
